apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: cdn
type: Opaque
stringData:
  azurestorageaccountname: {{ .Values.storageAccountName | quote }}
  azurestorageaccountkey: {{ .Values.storageAccountKey | quote }}
