apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-file-pv-cdn
  namespace: cdn
spec:
  capacity:
    storage: {{ .Values.storageQuota | toString }}Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-storage-secret
    shareName: {{ .Values.fileshareName | quote }}
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file-pvc
  namespace: cdn
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: {{ .Values.storageQuota | toString }}Gi
