apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      initContainers:
        - name: init-caddy-dir
          image: busybox
          command: ['sh', '-c', 'mkdir -p /etc/caddy']
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy
      containers:
        - name: caddy
          image: caddy:2
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
            - name: caddy-certs
              mountPath: /data/caddy
          ports:
            - containerPort: 80
            - containerPort: 443
      volumes:
        - name: caddy-config
          configMap:
            name: caddy-config
        - name: caddy-certs
          persistentVolumeClaim:
            claimName: caddy-certs
