apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_HOST: {{ .Values.host | quote }}
  POSTGRES_PORT: {{ .Values.port | toString | quote }}
  POSTGRES_USER: {{ .Values.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.password | quote }}
  POSTGRES_DB: {{ .Values.db | quote }}
