apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.0
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - name: redis-storage
              mountPath: /data
            - name: redis-config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
          args: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          resources:
            requests:
              memory: "512Mi"
              cpu: "800m"
            limits:
              memory: "2Gi"
              cpu: "1500m"
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
        - name: redis-config
          configMap:
            name: redis-config

      tolerations:
        - key: "f4sv2"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      nodeSelector:
        role: "f4sv2"
