apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: bitnami/rabbitmq:3.13.7
          ports:
            - containerPort: {{ .Values.port }}
            - containerPort: {{ .Values.managementPort }}
          volumeMounts:
            - mountPath: /bitnami/rabbitmq
              name: rabbitmq-storage
            - name: rabbitmq-config
              mountPath: /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5

          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config
      tolerations:
        - key: "f4sv2"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      nodeSelector:
        role: "f4sv2"
